# Usamos la imagen de Nginx para servir los archivos estáticos
FROM nginx:alpine

# Copiamos los archivos de la aplicación frontend en el contenedor
COPY ./ /usr/share/nginx/html

# Exponemos el puerto 80
EXPOSE 80
