version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pedidos
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  server_norte:
    build:
      context: ./backend/server_norte
    depends_on:
      - kafka
      - mysql
    environment:
      KAFKA_BROKER: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: pedidos
      SUCURSAL : NORTE

  server_centro:
    build:
      context: ./backend/server_centro
    depends_on:
      - kafka
      - mysql
    environment:
      KAFKA_BROKER: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: pedidos
      SUCURSAL : CENTRO

  server_sur:
    build:
      context: ./backend/server_sur
    depends_on:
      - kafka
      - mysql
    environment:
      KAFKA_BROKER: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: pedidos
      SUCURSAL : SUR


  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
      - mysql
    environment:
      KAFKA_BROKER: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: pedidos

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - server_norte
      - server_centro
      - server_sur
    restart: always

volumes:
  mysql_data:
